services:
  renovabit-postgres:
    container_name: renovabit-postgres
    image: postgres:18.1
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - ./data-postgres:/var/lib/postgresql/
    networks:
      - renovabit

  renovabit-api:
    container_name: renovabit-api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env.local
    depends_on:
      - renovabit-postgres
    networks:
      - renovabit

networks:
  renovabit:
    name: renovabit
    driver: bridge
